version: '3'

services:
  php:
    container_name: php
    build:
      context: ./php
      args:
        - PHP_VERSION=7.4
        - PHP_COMPOSER_VERSION=2.0.9
        - NODE_VERSION=14.15.0
    volumes:
      - ../services/service:/var/www
    ports:
      - 6001:6001
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ../services/service:/var/www
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql-primary:
    image: mysql:5.7
    container_name: mysql-primary
    ports:
      - 3306:3306
    volumes:
      - ./mysql-primary/var/lib/mysql:/var/lib/mysql
      - ./mysql-primary/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-primary/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
